import argparse
import os
import sys
from pathlib import Path

from pipenv import environments
from pipenv.cli.options import (
    apply_default_categories,
    apply_env_vars,
    build_parser,
    build_state,
)
from pipenv.utils import console, err
from pipenv.utils.environment import load_dot_env
from pipenv.utils.processes import subprocess_run

with console.capture() as capture:
    console.print("[bold]pipenv[/bold]", end="")

prog_name = capture.get()

LOCK_HEADER = """\
#
# These requirements were autogenerated by pipenv
# To regenerate from the project's Pipfile, run:
#
#    pipenv requirements {options}
#
"""


LOCK_DEV_NOTE = """\
# Note: in pipenv 2020.x, "--dev" changed to emit both default and development
# requirements. To emit only development requirements, pass "--dev-only".
"""


def do_py(project, system=False, bare=False):
    if not project.virtualenv_exists:
        err.print(
            "[red]No virtualenv has been created for this project[/red] "
            f"[yellow bold]{project.project_directory}[/yellow bold] "
            "[red] yet![/red]"
        )
        sys.exit(1)

    try:
        (print if bare else console.print)(project._which("python", allow_global=system))
    except AttributeError:
        console.print("No project found!", style="red")
        sys.exit(1)


def _open_editor(filename):
    """Open filename in the user's editor (replaces click.edit)."""
    pass


def cmd_install(args, state):
    pass


def cmd_remove(args, state):
    from pipenv.utils.virtualenv import cleanup_virtualenv

    if state.project.s.PIPENV_USE_SYSTEM or environments.is_in_virtualenv():
        console.print(
            "You are attempting to remove a virtualenv that "
            "Pipenv did not create. Aborting.",
            style="red",
        )
        sys.exit(1)
    if state.project.virtualenv_exists:
        loc = state.project.virtualenv_location
        console.print(f"[bold]Removing virtualenv[/bold] ([green]{loc}[/green])...")
        with console.status("Running..."):
            cleanup_virtualenv(state.project, bare=True)
        return 0
    else:
        err.print(
            "No virtualenv has been created for this project yet!",
            style="red bold",
        )
        sys.exit(1)


def cmd_upgrade(args, state):
    pass


def cmd_uninstall(args, state):
    pass


def cmd_lock(args, state):
    pass


def cmd_shell(args, state):
    pass


def cmd_activate(args, state):
    pass


def cmd_run(args, state, extra_args=None):
    pass


def cmd_check(args, state):
    pass


def cmd_audit(args, state):
    pass


def cmd_update(args, state):
    pass


def cmd_graph(args, state):
    pass


def cmd_open(args, state):
    pass


def cmd_sync(args, state):
    pass


def cmd_clean(args, state):
    pass


def cmd_scripts(args, state):
    pass


def cmd_verify(args, state):
    pass


def cmd_requirements(args, state):
    pass


def cmd_pylock(args, state):
    pass


_DISPATCH = {
    "install": cmd_install,
    "remove": cmd_remove,
    "upgrade": cmd_upgrade,
    "uninstall": cmd_uninstall,
    "lock": cmd_lock,
    "shell": cmd_shell,
    "activate": cmd_activate,
    "run": cmd_run,
    "check": cmd_check,
    "audit": cmd_audit,
    "update": cmd_update,
    "graph": cmd_graph,
    "open": cmd_open,
    "sync": cmd_sync,
    "clean": cmd_clean,
    "scripts": cmd_scripts,
    "verify": cmd_verify,
    "requirements": cmd_requirements,
    "pylock": cmd_pylock,
}


def _get_subparser(parser, name):
    """Return the subparser for *name*, or None if not found."""
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action.choices.get(name)
    return None


def cli():
    """Main argparse-based entry point for pipenv."""
    from pipenv.utils.display import format_help
    from pipenv.utils.shell import system_which
    from pipenv.utils.virtualenv import do_where, warn_in_virtualenv

    # Handle legacy _PIPENV_COMPLETE env var from the Click-based CLI.
    # Since pipenv 2026.5.0, shell completion uses argcomplete instead.
    # Detect the old mechanism and provide a helpful migration message.
    if os.environ.get("_PIPENV_COMPLETE"):
        print(
            "Shell completion has changed in pipenv >= 2026.5.0.\n"
            "The _PIPENV_COMPLETE environment variable is no longer supported.\n"
            "\n"
            "To enable shell completion, install the completion extra and use:\n"
            "  pip install pipenv[completion]\n"
            '  eval "$(register-python-argcomplete pipenv)"\n'
            "\n"
            "For more details, see: https://pipenv.pypa.io/en/latest/shell.html#shell-completion",
            file=sys.stderr,
        )
        sys.exit(1)

    parser = build_parser()

    # Enable shell completion when argcomplete is installed.
    # Users activate it once with: eval "$(register-python-argcomplete pipenv)"
    # Install the optional dependency with: pip install pipenv[completion]
    try:
        import argcomplete

        argcomplete.autocomplete(parser)
    except ImportError:
        pass

    argv = sys.argv[1:]

    # Use parse_known_args so that extra args for 'run'/'shell' pass through.
    args, remaining = parser.parse_known_args(argv)

    # Shared options use argparse.SUPPRESS as their default so that subparser
    # defaults never overwrite values already parsed by the root parser
    # (e.g. ``pipenv --python 3.11 sync``).  Ensure the attributes exist
    # before env-var overlay and state building.
    for _attr in ("python", "pypi_mirror", "verbose", "quiet", "clear", "system"):
        if not hasattr(args, _attr):
            setattr(args, _attr, None)

    # Overlay PIPENV_* env vars for any attribute still at its sentinel (None).
    apply_env_vars(args)

    # Build the State object (validates python path, pypi mirror, verbosity).
    state = build_state(args)

    load_dot_env(state.project, quiet=state.quiet)

    if "PIPENV_COLORBLIND" in os.environ:
        err.print(
            "PIPENV_COLORBLIND is deprecated, use NO_COLOR"
            " per https://no-color.org/ instead",
        )

    warn_in_virtualenv(state.project)

    cmd = args.command

    # ── Root-level (no subcommand) ────────────────────────────────────────────
    if cmd is None:
        if getattr(args, "help", False):
            console.print(format_help(parser.format_help()))
            return 0

        if args.man:
            if system_which("man"):
                path = Path(__file__).parent.parent / "pipenv.1"
                os.execle(system_which("man"), "man", str(path), os.environ)
                return 0
            else:
                err.print(
                    "man does not appear to be available on your system.",
                    style="bold yellow",
                )
                return 1

        if args.envs:
            console.print(
                "The following environment variables can be set, to do various things:\n"
            )
            for key in state.project.s.__dict__:
                if key.startswith("PIPENV"):
                    console.print(f"  - {key}", style="bold")
            console.print(
                "\nYou can learn more at:\n   "
                "[green]https://pipenv.pypa.io/en/latest/advanced/#configuration-with-environment-variables[/green]",
            )
            return 0

        if args.where:
            do_where(state.project, bare=True)
            return 0

        if args.py:
            do_py(state.project, bare=True)
            return 0

        if args.support:
            from pipenv.help import get_pipenv_diagnostics

            get_pipenv_diagnostics(state.project)
            return 0

        if state.clear:
            from pipenv.routines.clear import do_clear

            do_clear(state.project)
            return 0

        if args.venv:
            if not state.project.virtualenv_exists:
                err.print(
                    "[red]No virtualenv has been created for this project[/red]"
                    f"[bold]{state.project.project_directory}[/bold]"
                    " [red]yet![/red]"
                )
                sys.exit(1)
            print(state.project.virtualenv_location)
            return 0

        if args.rm:
            err.print(
                "Warning: [yellow]--rm[/yellow] is deprecated and will be removed in a future release. "
                "Use [green]`pipenv remove`[/green] instead.",
            )
            cmd_remove(args, state)
            return 0

        if state.python or state.site_packages:
            from pipenv.utils.project import ensure_project

            ensure_project(
                state.project,
                python=state.python,
                warn=True,
                site_packages=state.site_packages,
                pypi_mirror=state.pypi_mirror,
                clear=state.clear,
            )
            return 0

        # No flags: show help
        console.print(format_help(parser.format_help()))
        return 0

    # ── Subcommand --help ─────────────────────────────────────────────────────
    if getattr(args, "help", False):
        sub = _get_subparser(parser, cmd)
        if sub is not None:
            console.print(format_help(sub.format_help()))
        else:
            console.print(format_help(parser.format_help()))
        return 0

    # ── Unrecognised arguments (except for 'run' which passes them through) ──
    if remaining and cmd != "run":
        parser.error(f"unrecognized arguments: {' '.join(remaining)}")

    # ── Dispatch ──────────────────────────────────────────────────────────────
    handler = _DISPATCH.get(cmd)
    if handler is None:
        parser.error(f"No such command: {cmd!r}.")

    if cmd == "run":
        handler(args, state, extra_args=remaining)
    else:
        handler(args, state)


if __name__ == "__main__":
    cli()
